services:
  x-base-web: &base-web
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    env_file:
      - ./.env/.dev-sample
    volumes:
      - ./services/backend:/app
    depends_on:
      - redis
      - db
    networks:
      - my-network
    command: ["/start.sh"]

  # Fast API
  web:
    <<: *base-web
    ports:
      - "8010:8000"
  # celery worker
  celery_worker:
    <<: *base-web
    image: fastapi_celery_worker
    command: /start-celeryworker.sh

  # Celery beat
  celery_beat:
    <<: *base-web
    image: fastapi_celery_beat
    command: /start-celerybeat.sh

  # Postgres
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fastapi_celery
      - POSTGRES_USER=fastapi_celery
      - POSTGRES_PASSWORD=fastapi_celery
    networks:
      - my-network

  # Redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
