[tool.black]
line-length = 119
extend-exclude = ["venv", "alembic"]


[tool.isort]
profile = "black"
multi_line_output = "VERTICAL_HANGING_INDENT"
force_grid_wrap = 2
line_length = 119
skip = ["venv", "alembic"]


[tool.ruff]
select = ["E", "F", "B", "ERA"]
line-length = 119
ignore = ["B008"]
extend-exclude = ["venv", "alembic"]

[tool.pytest.ini_options]
markers = [
    "slow: mark test as slow to run (deselct with '-m \"not slow\"')",
]


[tool.pylint.main]
ignore = ["venv", "alembic"]
ignore-patterns = ["^/alembic/*.py"]
ignore-paths = "services/backend/alembic"
output-format = "colorized"

[tool.pylint.format]
max-line-length = 119

[tool.pylint."messages control"]
disable = [
    "line-too-long",
    "trailing-whitespace",
    "missing-function-docstring",
    "consider-using-f-string",
    "import-error",
    "too-few-public-methods",
    "redefined-outer-name",
    "missing-module-docstring",
]

[tool.pylint.reports]
output-format = "colorized"


[tool.flake8]
docstring-convention = "all"
ignore = ["D107", "D212", "E501", "W503", "W605", "D203", "D100"]
max-line-length = 119
extend-exclude = [
    "venv",
    "*/alembic/*.py",
    "__init__.py",
    "__pycache__",
]
per-file-ignores = [
    "__init__.py:F401",
]
