"""empty message

Revision ID: 27fefc78bdbe
Revises: 49206bf858e8
Create Date: 2024-09-16 07:16:31.552794

"""

from typing import (
    Sequence,
    Union,
)

# revision identifiers, used by Alembic.
revision: str = "27fefc78bdbe"
down_revision: Union[str, None] = "49206bf858e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
