"""empty message

Revision ID: 49206bf858e8
Revises:
Create Date: 2024-09-16 07:13:20.018012

"""
from typing import (
    Sequence,
    Union,
)

# revision identifiers, used by Alembic.
revision: str = "49206bf858e8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
